<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Package">
    <PackageId>Alexaka1.Distroless.HealthChecks</PackageId>
    <Description>A simple .NET app, that is able to perform health checks inside a distroless container that only has the .NET runtime as a dependency.</Description>
    <Version>1.1.1</Version>
    <Authors>Alex Martossy</Authors>
    <PackageTags>docker;healthcheck;dotnet;distroless;chiseled-container</PackageTags>
    <PackageProjectUrl>https://github.com/alexaka1/distroless-dotnet-healthchecks</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AnalysisLevel>latest</AnalysisLevel>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Label="AOT" Condition="'$(Configuration)' == 'Release'">
    <PublishAot>true</PublishAot>
    <OptimizationPreference>Speed</OptimizationPreference>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>
    <TrimmerRemoveSymbols>true</TrimmerRemoveSymbols>
    <DebugSymbols>false</DebugSymbols>
    <DebugType>None</DebugType>
    <!-- https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options#trim-framework-library-features-->
    <DebuggerSupport>false</DebuggerSupport>
    <MetricsSupport>false</MetricsSupport>
    <StackTraceSupport>false</StackTraceSupport>
  </PropertyGroup>

  <PropertyGroup Label="Source generation">
    <EnableRequestDelegateGenerator>true</EnableRequestDelegateGenerator>
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.UI.Core" Version="9.0.0"/>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="9.0.4"/>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.4"/>
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.4"/>
  </ItemGroup>

  <PropertyGroup Label="Supply chain auditing">
    <!--    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>-->
    <NuGetAudit>true</NuGetAudit>
    <NuGetAuditMode>all</NuGetAuditMode>
    <NuGetAuditLevel>low</NuGetAuditLevel>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\.dockerignore">
      <Link>.dockerignore</Link>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.Development.json" Condition="'$(Configuration)' == 'Debug'">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
